### ISSUE TITLE
To do: Inline thread expansion

### ISSUE THREAD

**Issue by ghost** [spootTheLousy/saguaro#10]
Inline thread expansion by clicking on the "x Posts and y Images omitted. Click to reply." message.

**Comment by Apogate** [comment]
@RePod  mentioned jury rigging thread_updater.js to add this functionality

**Comment by RePod** [comment]
Aside from jQuery, a _class_ dedicated to thread generation would probably make this ezpz.

Simply have jQuery load the pre-generated thread and replace the old instance on the index.
