### ISSUE TITLE
NEAT IDEA ISSUE

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#105]
1) Move posts from thread.
- Simple enough as modifying resto in sql

**Comment by RePod** [comment]
Do you mean changing a reply to an OP? That seems risky and not worth doing.

**Comment by Apogate** [comment]
2) Image/thumbnail rebuilding

I think this could be a simple foreach statement? That calls thumb.php for every image in the thumb/ dir

yea
