### ISSUE TITLE
Clicking a post # in view thread mode is messed up

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#106]
Check it out on the demo board

**Comment by RePod** [comment]
- ~~[_core/thread/post.php](https://github.com/spootTheLousy/saguaro/blob/master/_core/thread/post.php#L35-L39)~~ **DONE**
  - Possibly change out _$resno_ for _$this->inIndex_, which is what _formatOP()_ in the same class does (which may be why OPs aren't affected).
- [_core/thread/autolink.php](https://github.com/spootTheLousy/saguaro/blob/master/_core/thread/autolink.php)

**Comment by RePod** [comment]
Did 0d660c37eb39093cc05e6b681569bc0284868e4a fix this?

**Comment by Apogate** [comment]
Allegedly.

Case closed
