### ISSUE TITLE
Users can create posts witout any text and image

### ISSUE THREAD

**Issue by malamut2014** [spootTheLousy/saguaro#108]
Like this:<br />
![2015-09-19 14 58 52](https://cloud.githubusercontent.com/assets/9732705/9976074/f96d53a8-5ede-11e5-9d1d-50ebba49c389.png)

**Comment by RePod** [comment]
Steps on how to replicate it would be nice.

Your error log (preferably with stack traces) would also be useful.  
If you can't access logs but know how to replicate it, you can enable logging at the bottom of the latest _config.php_.

**Comment by malamut2014** [comment]
When posting i get this
`Warning: Missing argument 2 for Log::update(), called in /var/www/html/saguaro_webm/_core/log/log.php on line 233 and defined in /var/www/html/saguaro_webm/_core/log/log.php on line 19`
`Updating`
Logs:
`[Sat Sep 19 18:03:52.028391 2015] [:error] [pid 14909] [client 127.0.0.1:58002] PHP Deprecated:  mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/html/saguaro_webm/imgboard.php on line 49, referer: http://localhost/saguaro_webm/res/28.html
[Sat Sep 19 18:03:52.188846 2015] [:error] [pid 14909] [client 127.0.0.1:58002] PHP Warning:  Missing argument 2 for Log::update(), called in /var/www/html/saguaro_webm/_core/log/log.php on line 233 and defined in /var/www/html/saguaro_webm/_core/log/log.php on line 19, referer: http://localhost/saguaro_webm/res/28.html`

**Comment by Apogate** [comment]
This seems to be an issue with Staff safety check overrides.

From what I've tested on our [latest build](http://boards.saguaro.tk/bta]), this can only happen when you are logged in as a staff member. Since staff members dont have image, comment or flood checks, they can do weird things like this.

Here is the attached error @RePod 
![](http://i.imgur.com/ciIOujv.png)

**Comment by RePod** [comment]
Doesn't seem like a bug, more like a feature.

**Comment by Apogate** [comment]
It /could/ be a flood issue if the admin account was compromised, but if the admin account is compromised, you have bigger problems anyway. I'll close this for now as I can't replicate it while not logged in as a staff member on the latest build
