### ISSUE TITLE
Captcha doesn't disable for admin form

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#109]
Probably an issue with regist. Should be a simple fix using valid()

**Comment by RePod** [comment]
- [Regist](https://github.com/spootTheLousy/saguaro/blob/master/_core/regist/regist.php#L10-L16)

Captcha should not determine whether it should be used or not. Captcha currently generates the image/code when viewed directly (PostForm) and validates it when the class is loaded (Regist).

It's Regist's responsibility to determine if Captcha should be used.

> catpcha

**Comment by Apogate** [comment]
Fixed in 8e7389cf3283748d4bc75ecfab6f524eb27f07f3
