### ISSUE TITLE
TO-DO: Fix config file value types.

### ISSUE THREAD

**Issue by RePod** [spootTheLousy/saguaro#11]
Currently some variables (mostly boolean) are invalid.

What is represented as a 0 or 1 is sometimes encapsulated as a string, instead of being either:
- **0/1**
- **false/true**

Also, normalization of quoting. Preferably ", escaping as needed.

**Comment by RePod** [comment]
If it's resolved why is it still open.

RePod 1, @Apogate 0.

**Comment by Apogate** [comment]
sometimes its just hard to say goodbye
