### ISSUE TITLE
Clean up report()

### ISSUE THREAD

**Issue by RePod** [spootTheLousy/saguaro#115]
Before proceeding, see [this comment](https://github.com/spootTheLousy/saguaro/issues/64#issuecomment-143574619) in #64.

---
- Function names should be cleaned up to avoid redundancy:
  - Report->report_submit()
  - Report->report_check_ip()
  - Report->report_post_exists()
  - Report->report_post_isSticky()
- Should be more self-contained.
  - At the time of writing a majority of the processing is done in _imgboard.php_, which is bad.
  - See [Catpcha's implementation in Regist](https://github.com/spootTheLousy/saguaro/blob/master/_core/regist/regist.php#L19) for a good example of what it should be.
- There should be very little functional code actually in _imgboard.php_

As for implementing it, I would recommend: (in _imgboard.php_'s switch statement)

``` PHP
case 'report':
    require_once(CORE_DIR . "/admin/report.php");
    $report = new Report;

    $report->process();
    break;
```

Using `global` within the class as needed.

**Comment by Apogate** [comment]
This was on the todo list

ITS A FEATURE

**Comment by RePod** [comment]
Should have been done properly the first time, as now it needs to be moved anyway.

**Comment by Apogate** [comment]
SHOULD be up to your standards in eddbd8c29b9f68e7254befcf10dcd6700f36080a.

Going to close this for now.

**Comment by RePod** [comment]
It can be optimized, but yes this is a start.
