### ISSUE TITLE
HTML To do list

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#122]
- [x] Render capcodes in CSS to reduce log space
- [x] Fix capcode+tripcode bug where admins putting a trip with their name changes the color of the preceding cap.

more later

**Comment by Yushe** [comment]
Didn't know where to put this so I'm just going to put this here, boardlist.txt doesn't work anymore.

**Comment by RePod** [comment]
Keep in mind it's not hardcoded, BOARDLIST must be changed in the config.

On this note, it should either be updated in the config or removed from the repo.

**Comment by RePod** [comment]
~~I'll update test.php to create the file (not its contents) at least if it's defined.~~ 48fee8e43ac4c0e771cdac8d75a5bce70bc1e087
