### ISSUE TITLE
Threads not expiring properly.

### ISSUE THREAD

**Issue by RePod** [spootTheLousy/saguaro#123]
Scenario:
- **PAGE_DEF** 2 (threads per page)
- **PAGE_MAX** 3 (max pages)

Result:
- First two pages ordered properly via bump order.
- Third page has a single thread stuck that does not expire.
- In another testing board, getting **$S_BADDELPASS** when _posting_ in a similar situation.
- Bumping at this point is destructive, but after that new threads can be posted again.

Have not determined if this was from a recent change.

Might also have to due with caching issues, more tonight at 11: 8615252286d9383ce47e3fbe8e9220c857ea1236

**Comment by Apogate** [comment]
Wow, whos idea was this @RePod

**Comment by RePod** [comment]
Yours, clearly. Since DeletePost is part of the problem.

**Comment by Apogate** [comment]
I cannot replicate it after commit 44455585a7110dc934e11a92c77f9b7f5a7da3c0

Aditionally, threads on the end of the last index page get marked for old (as they should be). But if they are bumped to the front from the edge, they still retain the legacy "Marked for deletion (old)" label.

Do we need to keep this message, as auto pruning is pretty much standard now?
