### ISSUE TITLE
Image Searching

### ISSUE THREAD

**Issue by Yushe** [spootTheLousy/saguaro#128]
The image searching icons when clicked they set the image you are looking for as the background, they don't search for the image.

There is no known way that I have found to get rid of the image once it has been set as the background.

**Comment by Apogate** [comment]
Remove **plugins/jquery/extras/bgmod.js** from the **jquery** folder

**Comment by Yushe** [comment]
@Apogate Why is the file still there if it doesn't work properly.

**Comment by Apogate** [comment]
Because it's cached in the browser if i remember correctly. Make sure all your tabs are closed and clear the browser cache. visit and refresh the page

**Comment by RePod** [comment]
It would be easier to check if it's (un)loaded by viewing the Admin page's source as it is not cached.
