### ISSUE TITLE
Clean up Regist valid() usage.

### ISSUE THREAD

**Issue by RePod** [spootTheLousy/saguaro#130]
It's called multiple times (and within files it loads), when the results could be cached instead.

Alternatively, valid() could be changed to return an array/object containing status:

``` PHP
[
    'moderator' => true,
    'janitor' => true,
    'admin' => false
];
```

Again, cache this once and work off it.

~~I haven't looked into valid() but I'd assume it's accessing the SQL server to do so which means it's happening multiple times per lookup, especially when checking multiple in succession.~~

I looked through valid() and was correct, the instance is per-call so each call is a unique request to the server.

I'm currently working on a User class as a central way of user instance handling. This will have the added benefit of only needing to be generated once per execution and potentially carry through multiple sessions. Either way it'll be a lot less SQL intensive than valid():

![screenshot_1](https://cloud.githubusercontent.com/assets/7897871/10688573/3e3c3ce6-7943-11e5-9170-030fe7179325.png)

**Comment by Apogate** [comment]
All valid calls in regist were replaced by the $moderator cache, which was set by a single valid call. This reduced the number of `valid()` SQL queries to 1 if the user was not a staff member, or 3 if the user was a staff member in order to determine what permissions they had.

**Comment by Apogate** [comment]
Regist is functionally different, this is outdated
