### ISSUE TITLE
Improvements And Suggestions

### ISSUE THREAD

**Issue by Yushe** [spootTheLousy/saguaro#131]
I have been thinking and here are some suggestions maybe add some features that 4chan-x has:
1. Quick Reply's
2. Thread Watcher
3. More Options In The Settings
4. File Boards Like /f/ on 4chan

What do you think?
I might think of more. :V

**Comment by RePod** [comment]
Quick reply exists but is currently broken until updated to support the new page generation.

However, it's not a priority for me and anybody can create/update existing javascript files (such as quicky reply) and easily integrate with settings menu.

**Comment by Yushe** [comment]
@RePod What about the other things?
(I really gotta learn how to code java)

**Comment by RePod** [comment]
> Java

There's no Java involved, Javascript is not Java.

Anything is possible, as long as people are willing to do it.
However, I'm not willing to do anything on your list.

My current priorities are the backend (what users don't see) to make it easier for @Apogate and myself to add features people _don't know they want._

However, I encourage you to try yourself (and send them back here as pull requests for the benefit of everyone).

**Comment by Yushe** [comment]
I will try to send simple fixes that you might've missed but I really don't know anything when it comes to .js files.
