### ISSUE TITLE
Main SQL Table Not Generating

### ISSUE THREAD

**Issue by Yushe** [spootTheLousy/saguaro#133]
So I'm trying to add another board to my site.
Go onto test.php and everything is fine but the main SQL table didn't generate for some reason, all the other tables were generated fine. (ban, mod and del)

**Comment by Apogate** [comment]
what does test.php say about the post table when you run it

**Comment by RePod** [comment]
> for some reason

There should be a number on the same line where it failed, which is an error code indicating what the problem was.

Keep in mind multiple boards can share the same database (the first thing attempted to be created), but not the same tables.

**Comment by Yushe** [comment]
This wasn't here before but it says: (1064) FAIL on the main table and now the "creating default accounts".

**Comment by RePod** [comment]
Error 1064 indicates the SQL query was invalid.

If this doesn't happen with the default config options, it's most likely something you've changed is causing it. For instance, what did you enter for **PREFIX** or **SQLDB**?

**Comment by Yushe** [comment]
@RePod 
The prefix is 3 because that is the board-dir.

The SQLDB is fine because as I said before (ban, mod and del) generated fine but the main table didn't.

**Comment by RePod** [comment]
Does this happen if you start with something other than a number, like _three_?

**Comment by Yushe** [comment]
All my other boards have generated fine I will try it without a number now and tell you if it works.

**Comment by Yushe** [comment]
It works now but I really don't know why it didn't want to generate the number 3 as a table.

Anyway just gonna let you know that the [ Toggle postform ] button doesn't work.

**Comment by Apogate** [comment]
Make sure main.js is loading properly. I suppose i should add a catch for that.

Closing this as the topic issue was resolved
