### ISSUE TITLE
Posting Errors

### ISSUE THREAD

**Issue by Yushe** [spootTheLousy/saguaro#135]
I tested posting and it was not working at all so I enabled debug mode to see what the problem was and this is what I got.

<code>Error #You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'posteruid' id="posterid" style="background-color:inherit; border-radius:10px;fon' at line 1 on query: insert into three (now,name,email,sub,com,host,pwd,ext,w,h,tn_w,tn_h,tim,time,md5,fsize,fname,sticky,permasage,locked,root,resto) values ('10/25/15(Sun)16:32 (ID:)','Anonymous','','test','test','','fd64c698','.png',152,180,0,0,'1445805170133',1445805170,'373a244064163ba4b6d5ed0ecbde4f37',30664,'1_21.png',0,0,0,now(),0)
Critical SQL problem!
1_21.png uploaded!

Updating page.
Your post may not appear immediately.</code>

Posts do not generate and as I said before in a different issue the admin "[ Toggle postform ]" doesn't work.
I have removed the tables a few times just to make sure it wasn't anything to do with the tables.

**Comment by Apogate** [comment]
6d365f6cb7c1ac065da40509e349a9e2f7c156d8 should have fixed it.

Ensure your **/plugins/jquery/main.js** and **admin.php** are updated to the most recent versions.

**Comment by Yushe** [comment]
Updated and it works except for ID's which display this: (ID:) but not the ID.

Edit: Names are under the subject for some reason.

**Comment by RePod** [comment]
[Source.](https://github.com/spootTheLousy/saguaro/blob/76c94f25d5ea9d809cf8ee6ff43ad38fe6a605d5/_core/regist/regist.php#L161)

**Comment by Apogate** [comment]
ID issue is fixed. Again, make sure ALL your components are updated. Closing this for now.

**Comment by RePod** [comment]
> Just update the single _imgboard.php_!

**Comment by Apogate** [comment]
@RePod YOU DID THIS

**Comment by RePod** [comment]
To be fair, nothing's changed.

People only need to copy over **_core/** or its contents and confirm replace.
