### ISSUE TITLE
Discussion: Globalconfig, local config

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#139]
A lot of config values are duplicates, and could be moved to a global-config which holds SQL information, filepathing, along with other values while a `board_config.php` would hold board specific settings like worksafe options, post/flood limits, page limits etc.

**Comment by RePod** [comment]
Okay RePod Jr.

Not a high priority at the moment. Especially if people are duplicating configs already.

Also forcing inheritance is bad because, for example, maybe a board is hosted on another SQL server.

**Comment by Apogate** [comment]
What about board specific options right into imgboard.php and adding more lines :^)

**Comment by RePod** [comment]
I had started this concept a long time ago with the modular configs, but somebody reverted that.
