### ISSUE TITLE
spoilers kills dumbledore

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#140]
fixing spoilers because the old system is absolutely ridiculous.

From what I understand, it appends SPOILER<> to the subject, and uses that as the basis to apply spoilers to thumbnails or some trash.

NEW SYSTEM:
If spoiler checkbox is set, **regist.php** will just store the `tim` name as spoiler.jpg. **Image.php** will call the spoiler thumbnail and resize it using the original thumbnail height/width via css.

**Comment by RePod** [comment]
There's no reason to resize anything.

Also, there's nothing wrong with adding new named columns (and purging unused ones). Most calls to rows fetch them as associative arrays/objects so we can refer to the column by name/key instead of index number.
