### ISSUE TITLE
Staff Management

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#141]
<h4>Current permissions tree:</h4>

| Access level (#) | Permission |
| --- | --- |
| **Janitor_this_board** (**1**) | 1. Bypass report flood, Delete posts via browser view |
| **Janitor** (**5**) | Allowed deletion across multiple boards, above permissions |
| **Moderator** (**10**) | Delete posts by IP, access to admin panel, thread tools (Sticky, lock, permasage), Imageless posting/flood bypass |
| **Manager** (**20**) | Global board rebuild, user management for those lower on the permission tree, above permissions |
| **Admin** (**50**) | Board creation, user management, above permissions |
| -------------------- | ------------------- |
| **Special Permissions** |  |
| **txtonly** | Allow the user to post threads without an image, (**Moderator+** have this by default) |
| **reportfloodbypass** | User can report in rapid succession without checks, (**Janitor+** have this by default) |

`(Special cases: txtonly, reportfloodbypass) < janitor_board < janitor < moderator < manager < admin`

<hr>

<h4>Proposed tree:</h4>

| Access level (#) | Permission |
| --- | --- |
| **janitor** (**1**) | Board-specific post deletion, report flood-bypass |
| **superjanitor** (**5**) | Global/multiple board post deletion, **Janitor+** |
| **moderator** (**10**) | Sticky, Lock, Ban panel (See IPs), Post info panel, Imageless posts, HTML tags in post, **Superjanitor+** |
| **manager** (**20**) | User management, Staff list, Page rebuilding, **Moderator+** |
| **admin** (**50**) | ???, **Manager+** |
| -------------------- | ------------------- |
| **Special Permissions** | Absorbed by Moderator level |

`janitor < superjanitor < moderator < manager < admin`

<hr>

The plan is to eventually make permissions modular and able to be individually set per user, rather than blanket-rank permissions, but that won't be viable until the **user.php** class is finalized.

<h4>Apo Checklist<h4>
- [x] User management class (**/admin/staff.php**)
  - [x] Add users
    - [x] Hashes password based on SaguaroCrypt method
  - [x] Remove users
  - [x] Panel staff list for Manager+
  - [ ] Restructured permissions tree
    - [ ] Manager permission works again
  - [ ] Instances of valid() updated
    - [ ] Valid() accommodates new tree

shoo shoo repod

**Comment by Apogate** [comment]
Will be absorbed by impending user class.

**Comment by RePod** [comment]
> Impending

**Comment by Apogate** [comment]
it hangs over me like a cloud. a deadly future full of suffering
