### ISSUE TITLE
IDs And Quoting

### ISSUE THREAD

**Issue by Yushe** [spootTheLousy/saguaro#142]
ID's and quoting (>>) are still broken.
But as you see below the sage id (Heaven) does work.

![error](https://cloud.githubusercontent.com/assets/10089856/10994677/c0f392a6-846f-11e5-81dd-a4d826063689.png)

**Comment by RePod** [comment]
Quoting hasn't been fixed (yet), I don't know why you thought that.

**Comment by Yushe** [comment]
What about ID's I thought they were fixed.

**Comment by Apogate** [comment]
I made a mistake

The current formula for generating IDs gets the last number in the log in an archaic way, and uses that as part of the salt. If the previous post was deleted, or in your example, doesnt exist yet, then it returns a blank string.

**Comment by Apogate** [comment]
Gonna merge this with #145
