### ISSUE TITLE
Log: New log has odd deletion bug

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#144]
![Image](http://i.imgur.com/Oh8M6H6.png)

Deleting from index leaves ^ after deleting with the new log class format. It disappears upon visiting **imgboard.php**/force updating the index.

I'll eventually look into this unless @RePod knows what this would be offhand.

**Comment by Apogate** [comment]
~~I THINK this is caused by [Log having the deleted data in the array](https://github.com/spootTheLousy/saguaro/blob/master/_core/log/log.php#L30)~~

~~[Because the log array isn't being rebuild when it needs to be](https://github.com/spootTheLousy/saguaro/blob/master/_core/log/log.php#L270) ie, after a post is deleted.~~ 

the hunt for the truth continues

**Comment by RePod** [comment]
New log doesn't take Rebuild into consideration, at all.

**Comment by Apogate** [comment]
For testing purposes, commenting out [line 270 of /core/log/log.php](https://github.com/spootTheLousy/saguaro/blob/master/_core/log/log.php#L270) fixes this, as I thought, the cache isn't being properly regenerated after a post is deleted. Perhaps adding a flag to the cache rebuild, or running it from the deletion function would suffice.

**Comment by Yushe** [comment]
Oh yeah and I'm just letting you guys know that you can blank post again.

**Comment by Apogate** [comment]
> blank post again

@Yushe I just tested this on every one of your boards. As a regular user
you cannot blank post. You CAN blank post from any thread when you have logged in as a staff member. That is an intended feature

**Comment by Yushe** [comment]
@Apogate This is really weird I was able to do this on /r/ yesterday.

**Comment by RePod** [comment]
> For testing purposes, commenting out line 270 of /core/log/log.php fixes this, as I thought, the cache isn't being properly regenerated after a post is deleted. Perhaps adding a flag to the cache rebuild, or running it from the deletion function would suffice.

That is the flag. Somewhere needs to be calling `Log->update_cache(true);` but isn't.

This is an intended speed improvement though, as if it the cache doesn't need to be updated every time it's accessed then it won't be.

**Comment by Apogate** [comment]
I'll scour through the deletion code then, thank for the help

**Comment by Apogate** [comment]
@RePod  what the HECK does `$this->cache` do, I see it everywhere but as far as I can tell, it's never explicitly used

**Comment by RePod** [comment]
That's not a function, it's reading it.

It's where `Log->update_cache()` stores its output.

A lot of older code updated to use it store it in `$log` which is where it was stored previously in _imgboard.php_. `$log = $my_log->cache` simply copies it into `$log` in the current scope (which is slow) instead of `global $log` that used to happen before.
