### ISSUE TITLE
Quotes, text processing

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#145]
- [ ] Interboard post linking works
- [x] Meme arrows quote properly
- [x] In-thread post quoting properly working

Review **/_core/regist/autolink.php** usage.

Discuss @RePod s proposal to shuffle all this into text processing class

**Comment by Apogate** [comment]
5be6ed08f7b57e0ff8c78f51aa43562dcbad2f13

**Comment by Apogate** [comment]
I think I figured the problem out here:
- The `$log` cache isn't making it all the way to the autolink, which autolinking is dependent upon.
- Html special chars (`&gt;`) are being converted back to normal `>` before being handled by autolinking, which only searches for `&gt;`.

**Comment by RePod** [comment]
Keep in mind autolinking and TextProcessors are applied during the page generation after being read out of the cache, instead of being stored as such.

**Comment by Apogate** [comment]
anything with `preg` melts my simple mind. i can't fix this on my own.

@RePod pls help im begging you

**Comment by RePod** [comment]
Well we don't [want to use ereg](http://php.net/manual/en/function.ereg.php).

As for everything else, it's just standard regex. May be a good time to start [learning it.](https://imgs.xkcd.com/comics/regular_expressions.png)

**Comment by Apogate** [comment]
Resolved, #192
