### ISSUE TITLE
SaguaroQL - The great journey.

### ISSUE THREAD

**Issue by RePod** [spootTheLousy/saguaro#159]
**PR #161**

**Goal:**
- Use SaguaroQL wherever applicable, while maintaining consistency between MySQL and MySQLi.
- Eventually switch to MySQLi as the default.

**Why:**
- MySQL (not MySQLi) was deprecated around PHP 5.5 (removed in 7) in favor of MySQLi.
  - Without testing, one can assume Saguaro would not work at all on PHP 7.

**What needs to be changed:**
- [Everything.](https://github.com/spootTheLousy/saguaro/search?utf8=%E2%9C%93&q=mysql)
- Remove usage of `mysql_call()` which exists as legacy support that returns `$mysql->query()`.
  - Son of #64 - The issue that turned Saguaro around.

**How:**
- Searching for `mysql_` in all files is a good start.
  - No traces should be left, and be modified to use `$mysql` accordingly.
- `global $mysql` if available from the top-level.
  - Currently only Admin and Imgboard load it, so it's basically everywhere.
- Maintaining consistency with `$mysql` naming is also good.
- Instances of `fetch_array()` (which returns both of the below) should use either:
  - `fetch_row()` if only caring about indexes
  - `fetch_assoc()` if only caring about columns (which is 99% of the time)
  - Should save a bit of bandwidth, and a very tiny performance boost? Either way, we don't always need both.
- Most named functions are duplicated as expected in the SaguaroQL classes, with the exception of the backend selection.

**Functions to implement:**
- ~~`free_result`~~ 660a6ee65510c695a25d7a3780343981a0757436
- [`result` third argument](https://github.com/spootTheLousy/saguaro/commit/e5939d00585f64bb870e5a427c72ee8ea4bb2372#diff-1fca97dc90ed1d8bbc76d3521a90f697R78)

**Testing:**
- Does it work on MySQL and MySQLi?

If SaguaroQL lacks a function, it can be added. However, that function should be able to implemented for both MySQL and MySQLi to keep parity.

**Comment by RePod** [comment]
bb53a46b0fb07b69dd72ba194705e957f5a1021f dd72ea8b467387c2da6c1b8248cd6974ec9df688 Added `escape_string()`.

MySQLi cannot use this without having an active connection, as it pulls the server's char set to escape properly.

**Comment by Apogate** [comment]
See https://github.com/spootTheLousy/saguaro/tree/Convert-SaguaroQL

can i even link to branches

**Comment by Apogate** [comment]
> MySQLi cannot use this without having an active connection, as it pulls the server's char set to escape properly.

Would making the charset a config value solve this problem?

**Comment by RePod** [comment]
I don't know the exact answer to that, but either way it wouldn't be the optimal solution.

**Comment by Apogate** [comment]
Is this good to push to master?

**Comment by RePod** [comment]
About as good as anything else, so no.
This is probably the most important functional change so it needs a lot of testing.

**Comment by Apogate** [comment]
Action checklist for merging:

i have shit to do and this needs to get merged so here's the checklist for metaphorically everything that involves a databse

Testing SaguaroQL branch as is (Nov. 20, 2015), carried out with DEBUG_ENABLE on
- [x] Setup/installing
  - [x] generates all tables
  - [x] table checks
  - [x] user account checks
  - [x] default account inserted

**User-end:**
- [x] Creating thread
- [x] replying to thread
  - [x] with image
- [x] deleting OP thread
  - [x] From thread
  - [x] From index
- [x] deleting reply
  - [x] from thread
  - [x] from index
- [x] Reporting
  - [x] Reporting self
  - [x] IP check
  - [x] spam check
- [x] catalog works 47d4d95893181c92e86f6fe60f6c1279255905a7 Included tweak for hosts with strict standards enabled

**Administration:**
- [x] login works
  - [x] failed attempts logged
- [x] post list
  - [x] post info
  - [x] deleting posts
- [x] reports
  - [x] list report
  - [x] clear report
  - [x] report post info
- [x] users
  - [x] list user
  - [x] add user
  - [x] remove user
- [x] bans
  - [x] add a ban
  - [x] dupe ban checks 503bb2ab2003adef229e142f0a49b2a62ff5b040
  - [ ] bans expire **Warnings do, time bans untested**
  - [x] global bans work
  - [x] warns work
  - [x] bans actually prevent posting

**Under-the-hood:**
- [ ] log
- [x] page generation
  - [x] index generation
  - [x] thread generation
  - [x] updates properly
- [x] regist
  - [ ] flood checks
  - [x] staff perms checks
  - [x] inserts post properly
  - [ ] auto pruning
    - [ ] old pages deleted
- [x] imgboard ?res=# redirect

**Comment by Apogate** [comment]
Issues found:

Double check flood checks in regist, seems users can flood by default.

**Comment by Apogate** [comment]
`Strict Standards: Non-static method Footer::format() should not be called statically, assuming $this from incompatible context in xxxx/_core/page/page.php on line 34`
47d4d95893181c92e86f6fe60f6c1279255905a7 converted `Footer::format()` to `$footer->format()`

**Comment by Apogate** [comment]
Bans are FUCKED. moving on

**Comment by Apogate** [comment]
~~Post pruning via **core/regist/prune_old.php** is also broken, the index is updated with the new post but the new post information is not stored in the post table (what the hell), and the old post+its resources are deleted.~~

Auto pruning works, just not smoothly. Pruned posts leave a phantom similar to #144

**Comment by Apogate** [comment]
3dc69389f9aa85e73cf76f0e5b597bd9a43ce620

Fixes misc issues in banned.php

c371d948d7ec91d01b71856be0f276762fb358cd

Optimize, fix stupid setup in `checkBan()`, found in **/_core/admin/banish.php**

Bans work. @Yushe you were semi-right in #162, bans didn't set properly.

**Comment by Apogate** [comment]
503bb2ab2003adef229e142f0a49b2a62ff5b040

**admin.php** If an IP is already serving ban, don't insert new ban

**Comment by Apogate** [comment]
@RePod 

Final issue, saguaro registers posts normally, although on the upload success screen, this is what the user gets:

<hr>

![image](https://cloud.githubusercontent.com/assets/8524639/11316841/c6e7c26e-8fe5-11e5-9176-beaf0f4cc682.png)

<hr>

a bunch of mystery unreferenced null results. spooky.

**Comment by RePod** [comment]
Test.php currently does not use SaguaroQL, it uses MySQLi directly.

What do the checks mean in your checklist?

**Comment by Apogate** [comment]
> What do the checks mean in your checklist?

The feature was tested and displayed no error/threw no warnings

**Comment by RePod** [comment]
You're too slow.

**Comment by RePod** [comment]
> a bunch of mystery unreferenced null results. spooky.

Fixed in 61e6ed9582ae654e8b4e47f5ae092864f755aa83.

**Comment by RePod** [comment]
If this is merged this can be closed and new issues revolving around the changes can be made then.
