### ISSUE TITLE
Board tracking

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#163]
A lot of features could be implemented if we had a way to keep track of boards being made. Perhaps **test.php** integration or (lol) another sql table

**Comment by RePod** [comment]
I think it's beyond a single board's scope to be aware of other boards and be able to interact with/handle/care about their data.

**Comment by Apogate** [comment]
Not interact, just be aware of each other.

Even a simple setup would allow for things like automated board list generation, a centralized administration/ban system, and a bunch of other shit which would eliminate the need for excess duplicate files like an admin.php or banned.php for every board
