### ISSUE TITLE
Delete images when post is deleted

### ISSUE THREAD

**Issue by Yushe** [spootTheLousy/saguaro#164]
What that title says when posts are deleted the files of the image are not deleted.

**Comment by Apogate** [comment]
Holy hell i forgot about this bug

kind of a big deal. Don't doubt this is something to do with `imgonlydel` not making it all the way to the delete function since it was converted to a class.

**Comment by Apogate** [comment]
fun fact: this also fixes that weird bug where deleting an op image deleted all the reply images

shit's been haunting us since 0.98.0
