### ISSUE TITLE
br tags are broken

### ISSUE THREAD

**Issue by Yushe** [spootTheLousy/saguaro#169]
Here is a preview:
http://3chan.ml/r/res/75.html

It displays this in phpmyadmin.
&lt;br /&gt;

**Comment by RePod** [comment]
Probably a combination of the TextProcessors and various changes from `<br />` to `<br>`.

**Comment by Apogate** [comment]
Resolved in the next patch. I'll close this when it merges.

**Comment by Apogate** [comment]
#127
