### ISSUE TITLE
Using "Imgonly" flag in admin panel wipes all posts from the database

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#170]
I have no words

@Yushe be careful out there son

**Comment by Apogate** [comment]
Luckily, it deleted everything BUT images so /bta/'s history is preserved. I had backups of the table so nothing too damaging has been done.

**Comment by RePod** [comment]
Try using 8532c091cc0f3c93172131b7e926ec75283d6703 ([ZIP](https://github.com/spootTheLousy/saguaro/archive/8532c091cc0f3c93172131b7e926ec75283d6703.zip)) which is before SaguaroQL.

**Comment by Yushe** [comment]
Where is the "Imgonly" tag?

inb4 i don't use the admin panel that much to post i usually just change the name in phpmyadmin after posting normally then i rebuild all.

**Comment by Apogate** [comment]
Fixed in #173
