### ISSUE TITLE
Banned.php Broken

### ISSUE THREAD

**Issue by Yushe** [spootTheLousy/saguaro#176]
Appears white without debug mode on but if it is it says there are errors.
Edit: The error is really obvious "_core//admin" and because it is looking for banish.php

<code>Warning: require_once(_core//admin/banish.php): failed to open stream: No such file or directory

Fatal error: require_once(): Failed opening required '_core//admin/banish.php' 

http://boards.saguaro.tk/bta/banned.php

**Comment by Apogate** [comment]
b821733022c1741444363ca4abd501a74a95cc11
