### ISSUE TITLE
Updating jQuery suite

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#179]
The jQuery suite will be updated to accommodate the new HTML, This is going to be my focus for the next couple days.

**Checklist for all currently working jQuery plugins:**

**Images**
- [x] Image hover
- [x] Image search
  - [x] Image search icons
- [x] Image Expansion
- [x] Hide all non-image posts

**Quotes/Replying**
- [ ] Quote preview
- [ ] Backlinks
- [ ] Inline quote linking
- [x] Quick Reply
  - [x] Persistent?
- [ ] Auto-reload w/o thread updater

**Monitoring**
- [ ] Thread updater
  - [ ] Auto-update by default
  - [ ] Auto-scroll on update
- [x] Thread statistics

**Navigation**
- [ ] Custom board list

**Misc**
- [ ] Force post wrap
- [x] Custom CSS

**Comment by RePod** [comment]
- Image search icons
  - These are kill in favor of a (potentially programmable) dropdown.
- Thread statistics
  - Appears to work but appears in the wrong spot.
  - Also shown on the index.
- Force post wrap
  - Works.

**Comment by Apogate** [comment]
for testing purposes, I set up a pre-apogate build for html comparison [here](https://boards.saguaro.tk/old)

**Comment by Yushe** [comment]
Is the "Replies" text with a list of replies going to be re-added?

**Comment by Apogate** [comment]
When utility quotes are fixed, I suppose.

Or you can 

> "Implement it yourself" - RePod, 2015

**Comment by RePod** [comment]
A better start would be figuring out why the current one is broken.

I could take a few guesses, but mobile support definitely wasn't expected.
