### ISSUE TITLE
Fortune+greentext breaks fortune

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#183]
Minor bug, greentexting on line immediately before a fortune breaks the fortune HTML.

Since saguaro is otherwise stable and all major functions actually work properly now, I will be taking a break from working on the repo. The boards will still kept up and moderated. Unless spoot or RePod decide to make contributions, development will be going on hiatus indefinitely.

**Comment by Yushe** [comment]
The boards were deleted...

**Comment by Yushe** [comment]
webm uploading is broken when you upload a webm it says ".webm\ is not a valid WebM"

**Comment by RePod** [comment]
Either way it's using deprecated `<font>` tags instead of CSS, among other things.

As for what is actually breaking it, no idea. Probably best to fix it by changing the order that they happen.

**Comment by Apogate** [comment]
Resolved in #192. Allegedly
