### ISSUE TITLE
Convert require_once use to class autoloading spl_autoload_*

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#186]
I am unsure if this would be less efficient than what we have now since we load classes on a need basis, but I've been reading `require_once` is allegedly slower in comparison, especially with a larger number of requests.

I know Saguaro already iterates over an array to check what to include with the current setup, I am just unsure whether or not this would be more efficient. caring about muh performance starts today 

[27 requires currently in the repo](https://github.com/spootTheLousy/saguaro/search?p=1&q=require_once&type=Code&utf8=%E2%9C%93) 

http://php.net/manual/en/function.spl-autoload-register.php
http://php.net/manual/en/function.spl-autoload.php

Pros:
- Supposed performance increases.
- ?
  Cons:
- More lines to imgboard.php.
- ?

**Comment by RePod** [comment]
- This is for PHP 5.1.2 or higher, we'd have to drop PHP 4 support.
  - I also wouldn't recommend magically maintaining legacy support either.
  - If we drop PHP 4, should also convert the SQL backend to MySQLi. (fortunately 99% done)
- There's very little to notice speed improvements except from Log and SaguaroQL classes.
  - Auto-loading everything will increase memory footprint that we might not even need.

I'm fine with it, just my literal two cents.

---

There also seems to be something about lower casing class names? I don't know if this is referring to the included file or the literal class name after it's loaded.

According to the comments, it's just for the file paths and names.
Not a huge problem.

_Also_ there seems to be a few issues with autoloading and some other kind of cache which may or may not be available in every environment.

**Comment by Apogate** [comment]
http://stackoverflow.com/questions/6437134/autoload-vs-include-family

Looks like this _may_ not be all that useful to us after all, I'll keep looking into it.

**Comment by Apogate** [comment]
how foolish i was
