### ISSUE TITLE
Index not updating

### ISSUE THREAD

**Issue by Yushe** [spootTheLousy/saguaro#191]
http://boards.saguaro.tk/bta/index.html

http://boards.saguaro.tk/bta/imgboard.php

http://boards.saguaro.tk/bta/res/350.html

**Comment by Apogate** [comment]
This was a me issue, not a repository issue. Should be fixed.

**Comment by Yushe** [comment]
@Apogate I updated my board /r/ to the latest version of the master branch and I'm having the index updating issue.

**Comment by Apogate** [comment]
Go to /r/, delete any file that says index, index.html or index.html.html,

rebuild all pages from the panel and tell me what files are created

**Comment by Yushe** [comment]
I think it is working now, I'm not sure why the post I made didn't appear on the index for ages.

**Comment by Apogate** [comment]
might be your cache. dont forget to delete and rename your `.htaccess_sample` to `.htaccess` to get the latest anti-caching rules

**Comment by Yushe** [comment]
@Apogate I think it is something to do with my computer because I can see the posts fine on other devices.

I have cleared my cookies multiple times.

**Comment by Yushe** [comment]
@Apogate For some reason threads are showing but replys are not.

**Comment by Apogate** [comment]
I just tested /r/,

I believe you personally are having browser caching issues. 

I do not have a device with safari to test with, so I cannot do anything for it.

Try and see if you have the same issue with firefox?

**Comment by Yushe** [comment]
@Apogate I mainly use firefox I just tried jewgle chrome and I could see the new replys.

**Comment by Apogate** [comment]
then it is a caching issue
