### ISSUE TITLE
Chmod images after creation

### ISSUE THREAD

**Issue by xx1182** [spootTheLousy/saguaro#201]
First of all, when i run test.php it seems to work, but it remain a blank page.
Second:
when i try to make a post a bunch of errors appear.
Any solution?
![erro](https://cloud.githubusercontent.com/assets/6748908/13110483/9c2ac784-d580-11e5-878b-b9f4db279920.png)

**Comment by RePod** [comment]
Were you following [this](https://github.com/spootTheLousy/saguaro/wiki/Installing)?

As for the white screen when using test.php, delete .test_lockout in the same folder.

**Comment by xx1182** [comment]
Yes i was following that.
UPDATE:
After running test.php withouth .test_lockout i recive different errors:
1: from the admin page
![1error](https://cloud.githubusercontent.com/assets/6748908/13111077/113f4a24-d584-11e5-9342-8ed030fc9496.png)
2: And when posting(tho it posts successful):
![post](https://cloud.githubusercontent.com/assets/6748908/13111109/4acea79e-d584-11e5-9201-de0624ae332d.png)

Also, what are the default passwords?

**Comment by xx1182** [comment]
Well the first error can be changed just by modfying:
The mysql api to the new mysqli, witch can be pretty fast.
EDIT:
Sure they changed a lot in php, this requires a lot of work for the new api, nevermind.

about the others i don't know because i'm a newbie in php

**Comment by Apogate** [comment]
default account is username: admin password: guest

@RePod maybe we should add a config value to switch between mysql/mysqli? and default it to mysqli

**Comment by xx1182** [comment]
A bunch of errors from the admin page:
![post](https://cloud.githubusercontent.com/assets/6748908/13113364/05e71b24-d58f-11e5-88ec-36f93e6eaef8.png)
This seem like a really nice imageboard, in comparsion to other ones.
Do you guys have the same errors? or is just me?

Also when i click an image(to larger it) it gives me 404.

**Comment by Apogate** [comment]
Is debug mode on in your config? Those aren't necessarily errors, just PHP telling us we need to update some functions.

> seems really nice

  :3

**Comment by xx1182** [comment]
Btw i don't know why when i click an image it doesnt diplay correctly and insthed gives me img not found.
EDIT:
LOL forgot permissions.
And also you should implement a way to change admin password.
EDIT:
End the boardlist seems to display only in teh admin page

**Comment by Apogate** [comment]
Did you rebuild the pages after changing the contents of the board list in the panel?

**Comment by Apogate** [comment]
*of the board list in the panel?

**Comment by Yushe** [comment]
Saguaro and a lot of php scripts can't run on hostinger.

Find a better host.

**Comment by RePod** [comment]
@Apogate 

> maybe we should add a config value to switch between mysql/mysqli? and default it to mysqli

Or just drop MySQL, leave it in there for extreme backporting purposes, and update the PHP requirement to 5.x.

Without completely switching to it, it's hard to debug in such a way that they both work.

Currently _test.php_ doesn't use SaguaroQL and uses MySQLi directly.

@xx1182 

> And also you should implement a way to change admin password.

For the time being, you can do it in _test.php_ by modifying [this section.](https://github.com/spootTheLousy/saguaro/blob/75c7eba70b48ee494629b8e9b185980a0150a8fa/test.php#L18-L20)

Also worth noting most of what you're calling "errors" are, as what Apogate mentioned, not specifically errors but instead suggested improvements for things that will be errors in the future. Things shouldn't just be breaking if everything is configured properly.

**Comment by Yushe** [comment]
@RePod So is my site currently using mysqli?

**Comment by RePod** [comment]
No. When I made _test.php_ I didn't even consider using the old MySQL.

Therefore, _test.php_ uses pure MySQLi and _imgboard.php_ uses whatever is loaded (MySQL by default).
By extension, if a server can't make it past _test.php_ without a problem there's very little hope for the actual board (especially after we force MySQLi).

**Comment by Yushe** [comment]
@RePod How will I convert the database if I even have to?

**Comment by RePod** [comment]
Nope.

**Comment by xx1182** [comment]
I don't know if this has to do with the imageboard, but whenever i make a post the image uploaded (the one in src) get 600 permissions..(owner only)

**Comment by Apogate** [comment]
we'll push a fix for that in the new regist

**Comment by Yushe** [comment]
@xx1182 It might be a problem with the host.
Before I bought a host I used older versions of saguaro on hostinger and they worked fine: http://saguaroimgboard.tk/download/

**Comment by Apogate** [comment]
New regist handles this differently, gonna go ahead and close this 1.5 year old issue
