### ISSUE TITLE
Index Generation

### ISSUE THREAD

**Issue by Yushe** [spootTheLousy/saguaro#206]
Index generation still seems to not be working.

**Comment by RePod** [comment]
Is your board running from a subfolder of the root? Like, `mysite.com/board`?
I had a problem recently where running it directly on the site root messed it up due to one of the automated config options.

**Comment by Yushe** [comment]
I run it in a regular folder like all of my boards.

**Comment by RePod** [comment]
What's the redirected URL after accessing _imgboard.php_?

**Comment by Yushe** [comment]
It just goes to index.html like usual.

**Comment by Apogate** [comment]
What board?

**Comment by Yushe** [comment]
A secret test board that I use for testing stuff before updating the boards.

**Comment by RePod** [comment]
I would highly suggest forking this repository (by clicking the `Fork` button ![fork](https://cloud.githubusercontent.com/assets/7897871/13369114/3669a514-dcbf-11e5-8fd7-b4cb502ef201.jpg) in the top-right corner of the page) to work on instead of mirroring our commits into [your own](https://github.com/Yushe/3ch) (in favor of you other, outdated fork).

The direct benefit of doing this is you can fetch all our commits without mirroring them yourself.

It's hard to discern how you are modifying/tampering with the software and I refuse to support it otherwise starting now. And no, we simply cannot "trust you" to mirror our commits.

**Comment by Yushe** [comment]
The reason I have it there is so it is easier to update the site without having to keep adding my own code back to it, also I have tried the one on this repo and mine they both have the same issue.

**Comment by RePod** [comment]
What modifications are you making that can be integrated with Saguaro natively? I'll look into adding them.

**Comment by Yushe** [comment]
There just minor things like the footer and redtext that if you want I can make a pull for it.

**Comment by RePod** [comment]
I can whip up something for a custom footer. I don't know what redtext is referring to though.

**Comment by Yushe** [comment]
The footer is the disclaimer and the link to the credits I use.

Redtext:
https://github.com/Yushe/3ch/commit/a9c0a878015d763f51a00ba6b9888507d60e936a

**Comment by RePod** [comment]
`[b][size=4][color=darkred]text[/color][/size][/b]` should product similar results.  
Might need to shuffle around the order, since they're processed by how they're ordered in the actual file and not the string.

**Comment by Apogate** [comment]
I'm going to bet this is safe to close?
Probably. Yeah.

**Comment by Yushe** [comment]
@Apogate Index generation is still not working for me for whatever reason.

**Comment by RePod** [comment]
[Check server logs.](https://github.com/spootTheLousy/saguaro/wiki/Common-Problems-and-Solutions)

**Comment by Yushe** [comment]
@RePod I found the problem, I don't know how to update to mysqli so it is having problems connecting to the database because "mysql_connect()" is deprecated.

**Comment by RePod** [comment]
Try changing [these lines in imgboard.php](https://github.com/spootTheLousy/saguaro/blob/master/imgboard.php#L28-L29) to:

``` PHP
require_once(CORE_DIR . "/mysql/mysqli.php");
$mysql = new SaguaroMySQLi;
```

**Comment by Yushe** [comment]
<code>Warning: mysqli::query() expects parameter 1 to be string, object given in /var/www/html/test/_core/mysql/mysqli.php on line 41

Catchable fatal error: Object of class mysqli_result could not be converted to string in /var/www/html/test/_core/mysql/mysqli.php on line 44</code>

@RePod I got these errors on imgboard.php

**Comment by RePod** [comment]
Mind you, it hasn't been tested thoroughly.
I need more information (like what's calling it, or what you're doing) to see why it's doing that.

**Comment by Yushe** [comment]
The myql_connect() errors appear on admin.php.
<code>mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /var/www/html/test/_core/mysql/mysql.php on line 13</code>

Also the ipnotes table hasn't been created yet because mysql error 1071.
