### ISSUE TITLE
Multi-image drifting

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#210]
Adding multi image support, I suppose the best place tomstart is front end.

Considering adding a third party js library to handle file uploads, replacing the old upload fields with one drag and drop box

~~[Dropzone.js](http://dropzonejs.com) looks promising.
There's always the possibility of a homebrew solution as well.~~

Looking over regist now to see what needs to be added

**Comment by RePod** [comment]
Front-end is easy, just change the file select box to allow multiple. Done.

Worst case scenario we could add javascript that adds an additional file select box to the form if the last one is used.

In the back-end we'd have to iterate over each file uploaded (to a cap) and process them as normal.
Unfortunately we have no way to store additional file info currently.

**Comment by Apogate** [comment]
With multi-image on other platforms, they do not store any of the values like `tn_w/h`, `w/h` etc.

8 out of 18 rows are dedicated to image data in the database (almost half!)

With our setup current setup,multi-image is going to be difficult.

could we store multiple image data in comma delimited lists in one column?

for example, 3 images in one post with widths of 30, 40 and 50 would store the value 
`30,40,50` in the post's `w` SQL column 

and we'd just `explode()` the `w` value when building the thread

**Comment by RePod** [comment]
Is there any real reason to store them at all?

**Comment by Apogate** [comment]
i know [_core/thread/image.php](https://github.com/spootTheLousy/saguaro/blob/master/_core/thread/image.php) uses those values, I don't know where it's used anywhere else however.

Update: deleting the `height` and `width` HTML `<img>` attributes  (which are set with `tn_h` & `tn_w`) doesn't seem to do anything for the thumbnails on boards right now since the images are already resized.

We might not need to store them after all

**Comment by RePod** [comment]
Well before we axe them, consider why they needed to be stored to begin with.

**Comment by Apogate** [comment]
It appears the only reason `h`, `w`, `tn_h` and `tn_w` are stored is for image resolution in the image information.

![saasdasd](https://cloud.githubusercontent.com/assets/8524639/13896556/c307fb0e-ed65-11e5-80dd-306a558dc1f8.png)

Totally removing them from the table, everything except resolution info works fine it seems.

**Comment by RePod** [comment]
- Create new media table to handle file data.
- Purge post table of actual file data, make a new column in post table that references intended rows in media table.

Potential problems:
- Deleting individual files among a set will need to be accounted for back in the post table.
- If we intend to de-duplicate we need to make sure a user (or possibly admin) deleting a file doesn't touch the rest.

**Comment by RePod** [comment]
Status.

**Comment by Apogate** [comment]
Added, supported & resolved. hooray
