### ISSUE TITLE
OP email link doesn't appear

### ISSUE THREAD

**Issue by Yushe** [spootTheLousy/saguaro#219]
Probable known already anyway but janitors can post stickys and locked threads.

Also if you create a thread and use an email the name won't attach the mailto link. (replys to threads work though)

**Comment by Apogate** [comment]
Which branch & version of regist are you using?

**Comment by Yushe** [comment]
@Apogate Master

**Comment by Apogate** [comment]
> master

That's why. Use [stable](https://github.com/spootTheLousy/saguaro/tree/stable), I haven't gotten around to polishing new regist yet.

**Comment by Yushe** [comment]
@Apogate Ok, but email bug still works on stable.

**Comment by RePod** [comment]
How is the stable _ahead_ of master?

If we want stables, then just make them [releases](https://github.com/spootTheLousy/saguaro/releases).
Granted, you'd need a version number that doesn't rapidly increase from 1.1 to 1.3.15.
