### ISSUE TITLE
Regist doesn't parse newlines

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#242]
With latest master build, line breaks do not appear in comments.

Demo: https://saguaro.w4ch.xyz/s/

**Comment by RePod** [comment]
Too vague. If it's actually storing `\n`, which it should be, then it's even less of an issue,

Either:
 - Run `nl2br` before Regist stores it (increases space used and is more hard-coded in the long term)
 - Run `nl2br` after reading it out into Log/whatever (extra call, but more flexibility)
 - Client side javascript 👌 

Not my problem.

**Comment by Apogate** [comment]
you'eire' services are no longer required


note for myself later: 

https://github.com/spootTheLousy/saguaro/blob/master/_core/regist/regist.php#L207 https://github.com/spootTheLousy/saguaro/blob/master/_core/regist/inc/sanitize.php#L4
