### ISSUE TITLE
yushe bug hunt

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#256]

**Comment by Apogate** [comment]
regist doesnt check if threads are dead for replies

**Comment by Apogate** [comment]
catalog link in reply mode is broken

**Comment by RePod** [comment]
If these are issues from the switch to PDO they should be in its PR.

If they persist after merging, then they should be grouped together.

**Comment by Yushe** [comment]
The report button still doesn't work

**Comment by Apogate** [comment]
Merged with #211
