### ISSUE TITLE
What is gd and where do I put it?

### ISSUE THREAD

**Issue by JakeTrock** [spootTheLousy/saguaro#258]
is this GD? (https://github.com/libgd/libgd) if so, where do I put it(I'm missing it according to the config)

**Comment by Apogate** [comment]
[GD is a PHP library](http://php.net/manual/en/book.image.php) that should've shipped by default with your PHP installation. 

Side note, you should know this repository is very broken, so even if you get past the config setup, you're going to have issues getting it working. :(

**Comment by JakeTrock** [comment]
lol what should I use instead?

**Comment by Apogate** [comment]
I don't have a recommendation for you, sorry yo
