### ISSUE TITLE
Possibly replace gif2png with native PHP solution.

### ISSUE THREAD

**Issue by RePod** [spootTheLousy/saguaro#29]
http://php.net/manual/en/function.imagecreatefromgif.php
- With this standard implementation only the first frame would be retrieved.
  - Shouldn't be an issue as long as every GIF and their mom doesn't start with the same frame.
- One less file to manage (or not if this functionality is seperated from imgboard.php).
- No worries about _gif2png_'s licensing.

There are few references [[1]](//github.com/spootTheLousy/saguaro/blob/f79ecdeb4ceb477805b12727a605177d09f85f0a/imgboard.php#L2043) [[2]](//github.com/spootTheLousy/saguaro/blob/f79ecdeb4ceb477805b12727a605177d09f85f0a/imgboard.php#L2045) to _gif2png_ and an incomplete [native solution](//github.com/spootTheLousy/saguaro/blob/f79ecdeb4ceb477805b12727a605177d09f85f0a/imgboard.php#L2037-L2042) already in _imgboard.php_.
- What is the current behavior if _gif2png_ is not available while processing?
- Converting from GIF to PNG to JPG is a performance hit when it could be converted directly to JPG natively.
- PHP halts processing until the `@exec` command is finished, another performance hit.
- `@exec` is unsafe as it relies on communicating with an external application (that isn't PHP).

**Comment by ghost** [comment]
From what I've tested, the current native solution functions perfectly without gif2png as I have been unknowingly been running without gif2png for a couple of weeks now. I only realized I didn't have it upon checking this issue. 

Testing purposes: Processing a gif without gif2png and the current solution commented out throws  Error: Abnormal Reply.
![untitledz](https://cloud.githubusercontent.com/assets/8825917/8587723/f20b6f72-25cd-11e5-9e3d-790baf171c8c.png)

The dependency is more of a fallback if for some reason the host doesn't have imagick, but can be removed.

**Comment by RePod** [comment]
So there's no reason to keep it or code that uses it.

**Comment by Apogate** [comment]
Nope, #34

**Comment by RePod** [comment]
For context, this was apparently an issue back in 2003/2004 when [GD removed support for GIF](//libgd.github.io/pages/faq.html) which was later added back. _gif2png_ was used primarily everywhere as a workaround.

The chances of an installation having an affected version of GD are slim and should be met with a response of "update".

The more you know.
