### ISSUE TITLE
Change submission form file selection to prefer valid files by default.

### ISSUE THREAD

**Issue by RePod** [spootTheLousy/saguaro#36]
In general this will speed up browsing if users have several unsupported files (_ISO_, _ZIP_, _WMV_, etc.) around the desired file.
- [W3Schools](http://www.w3schools.com/jsref/prop_fileupload_accept.asp) (aye lmao) (uses DOM)
- [StackOverflow](//stackoverflow.com/a/10503561) (uses inline attributes)

Both methods allow specifying general types, such as `image/*` (which may be based on a browser's MIME types), and specific extensions:
- .gif
- .jpg/jpeg
- .png

The inline `accept` attribute (StackOverflow) would be better.

In an edge case where a supported file does not have the proper extension, users can still manually change the displayed files from their file selection window. We should not cater to users who would want to upload a PNG with a _txt_ extension (but we're not stopping them from trying).

---

Before:

![1_before](https://cloud.githubusercontent.com/assets/7897871/8589110/7f1c7372-25e0-11e5-9a05-cff890cf3981.jpg)

After: (`accept="image/*"`)

![2_after](https://cloud.githubusercontent.com/assets/7897871/8589111/7f1e7104-25e0-11e5-95c4-d47f1f6433e7.jpg)

`image/*` would probably be best choice to future proof it until non-image formats are supported (if at all).

**Comment by Apogate** [comment]
I like this concept, I'll begin testing on the test board
