### ISSUE TITLE
Discussion: Add country flags

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#38]
Contemplating adding this as a feature, in addition to changing how IDs appear (adding color).

Upside: 
- Flags

Downside: 
- 247 new files added

**Comment by RePod** [comment]
Requires the ability to reliably detect the country of origin.

I don't think PHP (or any library really) has the ability to do this without checking an external service (such as an IP Lookup service) which would be a pain to implement and might not be in the service's best interest, especially in bulk.

Alternatively, somewhere on the submission form users could select their country at the cost of "trust issues".

**Comment by Apogate** [comment]
Added in bf5213f2e0b3cdd9fd44a1f9d166695190b28e0d

**Comment by RePod** [comment]
This should probably be disabled be default.
