### ISSUE TITLE
Current ID system persistent across threads

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#40]
This inadvertently serves as a tripcode or username for those autismal enough to notice similar IDs between threads.

**Comment by RePod** [comment]
This also should probably be disabled by default.

**Comment by Apogate** [comment]
Proposed solution (before I forget)

IDs can be generated by using the host IP + the current thread number to maintain a persistent identity in a thread, but a unique and random identity outside a thread. 

As **_regist()**_ already predicts a new thread's OP #, simple tweak would allow **$no** to be used for OPs and **$resto** to be used for subsequent replies

im literally the best

**Comment by Apogate** [comment]
ill implement that trash ^^ tomorrow maybe

**Comment by RePod** [comment]
Might be worth including some else unique (server-side) to prevent other users from figuring out the IP.

**Comment by Apogate** [comment]
Current system uses the hosts IP as the salt in some backwards ass encryption like so:

    md5( crypt( ) );

This is just a change to the salt
