### ISSUE TITLE
Styleswitching needs to be revisited

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#44]
Current system relies on some [shitty switcher](http://www.dynamicdrive.com/) which also requires we add some [shitty disclaimer](https://github.com/spootTheLousy/saguaro/blob/master/imgboard.php#L1043) which triggers me deeply.

**Comment by RePod** [comment]
Missing the "Trigger Warning" label.

**Comment by RePod** [comment]
However, I would not implement it in raw Javascript. I'd prefer doing through jQuery (while still leveraging internal browser capabilities as much as possible).

If this situation were to happen the jQuery core would have to always be loaded, therefore negating the suite ever not being loaded. I'd also probably want it to utilize the suite settings as it has built in cookie management (which I wouldn't have to copy/paste) but that would require having the suite settings loaded.

**Comment by RePod** [comment]
Add a (non-configurable) human readable class to "actual" stylesheets that the page will be using.

With the switch to CSS sprites for the country icons my implementation is currently looking at all stylesheets and treating them as any other. A dedicated class will fix this.

For example:

``` HTML
<link class="main_style" rel="stylesheet" type="text/css" title="AS1" href="actual_sheet_1.css" />
<link rel="stylesheet" type="text/css" title="" href="supplementary_sheet.css" /> (such as flags.css)
<link class="main_style" rel="alternate stylesheet" type="text/css" title="AS2" href="actual_sheet_2.css" />
```

**Comment by RePod** [comment]
[Here's a current testing version for my styleswitcher.](//github.com/RePod/saguaro-jquery/blob/master/jquery/styleswitch.js)
- **Requires** jQuery to be loaded, but not the suite.
- Currently not set to comply with my previous comment of classes on changeable styles so it would break use of _flags.css_.
- Probably standards compliant.
