### ISSUE TITLE
Majority of Apache error logs are about undefined constants.

### ISSUE THREAD

**Issue by RePod** [spootTheLousy/saguaro#60]
At the time of writing, approximately 83% of my Apache error log is filled with these lines:

```
PHP Notice: Use of undefined constant DEBUG_MODE - assumed 'DEBUG_MODE' in saguaro/config.php on line 150, referer: saguaro/imgboard.php?mode=admin
```

While these could potentially be suppressed via the Apache/PHP configs, they shouldn't be happening in the first place.

**Comment by Apogate** [comment]
To fix this, I suggest converting config values from the current 

    define(BOARD, 'wew');
to something nicer such as

    $config['BOARD'] = 'wew'];

**Comment by RePod** [comment]
That would require updating all instances of the old code though. I'll think of something.

**Comment by RePod** [comment]
This is still happening, but I've also been slowly fixing other things spamming the log.

While this isn't a huge issue it does make finding issues harder as each instance is at least 2-3 lines (depending on where the stack trace happens) resulting in very huge and hard to read log files.

We could potentially just ignore these but that's just hiding the problem. (as said in first post)

**Comment by Apogate** [comment]
Resolved in latest [Stable](https://github.com/spootTheLousy/saguaro/blob/885c851bb7be4e674397b7f35ea2036886eb4800/config.php) branch.

PHP just wanted the `define(EXAMPLE, 'wew');` to have quotes, like so:

`define('EXAMPLE', 'wew');`

dont know if this harmed backwards compatibility for older versions of PHP, however.

Going to close the oldest issue now. woo

**Comment by RePod** [comment]
How could I be so blind!
