### ISSUE TITLE
Break down imgboard.php into specialized files and other cleanup.

### ISSUE THREAD

**Issue by RePod** [spootTheLousy/saguaro#64]
## Break down: (to non-/class)
- [x] [PostForm](//github.com/spootTheLousy/saguaro/blob/master/_core/postform.php)
  - ~~Currently lacks admin-specific functions (like sticky), have fun @Apogate~~
  - ~~Not tested enough for stable.~~ Pushed to stable anyway for bug testing.
- [x] [Thread generation](//github.com/spootTheLousy/saguaro/tree/master/_core/thread)
  - ~~Not yet integrated into Log.~~ #102 
- [x] [Regist + Tripcodes](//github.com/spootTheLousy/saguaro/tree/master/_core/regist) _~600 (~450 + ~150) lines_ (currently **non-class**)
  - [x] [thumb()](//github.com/spootTheLousy/saguaro/blob/master/_core/regist/thumb.php) _~100 lines_
  - [x] [prune_old()](//github.com/spootTheLousy/saguaro/blob/master/_core/regist/prune_old.php) _~46 lines_
- [x] [First run SQL table creation](https://github.com/spootTheLousy/saguaro/blob/f20272096a35bc0abe9b37b172ba389316717951/imgboard.php#L70-L200) _~100 lines_
  - ~~Ready to be removed, accurately recreated in [test.php](https://github.com/spootTheLousy/saguaro/blob/956eb2673411d55fc451b55b2b63dbf03e0a3b28/test.php#L143).~~ **DONE**
  - [x] [Rebuild queue?](https://github.com/spootTheLousy/saguaro/blob/f20272096a35bc0abe9b37b172ba389316717951/imgboard.php#L202-L213) **REPLICATED IN TEST.PHP**
- [x] [Log](//github.com/spootTheLousy/saguaro/blob/master/_core/log/) _~450 lines_ #77 **DONE** da1b91b3ce80eb9242a3a9310722f35761fbf285
  - [x] log_cache() _~150 lines_
  - [x] updatelog() _~400 lines_
- [x] Rebuilding _~80 lines_
  - [x] rebuild() _~41 lines_
  - [x] rebuildqueue_create_table() _~10 lines_ **REPLICATED IN TEST.PHP**
  - [x] rebuildqueue_add() _~8 lines_
  - [x] rebuildqueue_remove() _~8 lines_
  - [x] rebuildqueue_take_all() _~13 lines_
- [x] Administration/Moderation commands _~428 lines_
  - [x] valid() _~82 lines_
  - [x] admindel() _~180 lines_
  - [x] login() _~20 lines_
  - [x] userdel() _~59 lines_
  - [x] deletepost() _~87 lines_
- [x] Inter/intraboard linking and link normalization (Auto Linker) _~92 lines_
- [x] head()
- [x] foot()
- [x] error() 43ca7301aca853f2c926e1c0f7b9be0deddd57ba
- [x] report() #115 
- [x] mysql_call()
- To be determined...
## Relocate:

Intended to keep the root of the repository as clean as possible.
- [x] GeoIP: #67 
- Admin.php
- Banned.php
## Cleanup:
- [x] Large commented out sections that have been replaced functionality-wise.
- [x] oldvalid()
- [x] table_exist() _~9 lines_
  - Previously used for SQL table creation, but has been replaced entirely in _test.php_.
- [x] md5_of_file() _~15 lines_
  - [_core/regist/regist.php](//github.com/spootTheLousy/saguaro/blob/master/_core/regist/regist.php)
  - Not needed since _test.php_ checks for minimum PHP version.
  - For legacy PHP before 4.2.0 (April 22nd, 2002).
  - Only called twice (which could also be reduced to one call).
- [x] get_gd_ver() _~20 lines_
  - [_core/regist/thumb.php](//github.com/spootTheLousy/saguaro/blob/master/_core/regist/thumb.php)
  - Not needed since _test.php_ checks for minimum GD version.
  - For legacy GD before 2.x (April 5th, 2006).
  - Not future proof if GD's major version increases beyond _2_.
  - Only called once.
- [x] proxy_connect() **RE-IMPLEMENT IN REGIST**
  - [_core/regist/regist.php](//github.com/spootTheLousy/saguaro/blob/master/_core/regist/regist.php)
  - Potentially unsafe.
  - Used only by regist().

Update as needed.

---

Eventually all functionality will be accurately represented after being broken down.

**Advantages:**
- Cleaner, smaller, self-documenting code. (i.e. `$catalog->format()`)
- Easily scalable.
- Easier to track down problems and easier to fix/see results.
- Easier to update (a set of) individual files without worrying about who has done what to _imgboard.php_ and if it'll conflict.

**Disadvantages:**
- Lack of top-level scope, limited to what's available.
  - Potentially, things should be coded around this to not be a problem.

**Comment by Apogate** [comment]
oldvalid is still valid *badum tsss*

As it currently handles staff login.

**Comment by Apogate** [comment]
Suggest moving all the cleanup functions to a new file, **__core/general/legacy.php**_

**Comment by Apogate** [comment]
#72 Removes approximately 336 lines from imgboard.php, leaving the total at 1556.

**Comment by RePod** [comment]
[This still needs to be dealt with since test.php.](https://github.com/spootTheLousy/saguaro/blob/f20272096a35bc0abe9b37b172ba389316717951/imgboard.php#L70-L200)

Also could the [rebuild queue table](https://github.com/spootTheLousy/saguaro/blob/f20272096a35bc0abe9b37b172ba389316717951/imgboard.php#L202-L213) be relocated to _test.php_? If/when rebuilding is split into a specialized file (i.e. _rebuild.php_), does it need to create the table then or use the preexisting one?

**Comment by RePod** [comment]
Where is `rebuild()`? It's not in _imgboard.php_.

All the other rebuild functions are still in _imgboard.php_.

---

Seems it was removed in f20272096a35bc0abe9b37b172ba389316717951, see #77.

Index is failing to update unless _updatelog()_ is called from elsewhere.

**Comment by RePod** [comment]
> Suggest moving all the cleanup functions to a new file, _core/general/legacy.php

If you mean the stuff in my "Cleanup" section, all that can be discarded after they're accurately replaced, which most are.

I updated said entries with "**(ready to go)**".

**Comment by Apogate** [comment]
I think rebuild and friends can stay where they are, no?

**Comment by RePod** [comment]
What actually needs to use rebuilding though that would prevent them from being relocated?

Also this has been going on for 3 months now with very little progress for the latter. We are not able to test and fix problems from relocating things (such as rebuilding) until they _are_ relocated.

**Comment by RePod** [comment]
Log has been completely converted to a class and removed from _imgboard.php_ as of da1b91b3ce80eb9242a3a9310722f35761fbf285 which reduces imgboard to ~740 lines.

Legacy commands for Log were kept until everything else is updated to use the class.

~~Also, Log has a lot of (outdated and hard to update) duplicated code (such as index, thread, postform, etc) generation that can be replaced with their respective classes, so it can definitely get smaller.~~ **"LIKE 99% COMPLETE"**

**Comment by RePod** [comment]
@Apogate _[report()](https://github.com/spootTheLousy/saguaro/blob/master/imgboard.php#L222)_ needs to move.

---

Report's functionality should be as self-contained as possible and do no processing outside of it.

For example, `if ( !$report->report_post_exists( $no ) )` and `if ( $report->report_post_isSticky( $no ) )` should be relocated to be processed automatically inside the class.

To see a better example in action, see [Captcha in Regist](https://github.com/spootTheLousy/saguaro/blob/master/_core/regist/regist.php#L19) which does no processing (in Regist) other than if it returned valid (from the class).

Also this shouldn't be in imgboard at all, especially if it's such an edge case. This needs to be redone.

In the more perfect scenario, Report would be used like so: (in the switch at the bottom of _imgboard.php_)

``` PHP
case 'report':
    require_once(CORE_DIR . "/admin/report.php");
    $report = new Report;

    $report->process();
    break;
```

Using `global` within the class as needed.

---

Also, differentiating between `$_POST` and `$_GET` should be figured out. Unless we're specifically expecting a result from both, we should only cater to one. An example of this is Captcha now only reads from `$_POST` because it's expected to be included with the posting data. If we **need** to handle both it'd be best to use `$_REQUEST` which includes `$_POST`, `$_GET`, and `$_COOKIE`.

If the code is using the variables anyway, they should be requested from within the class. There's no reason to process a `$_GET`/etc and then pass it as an argument when it can just be processed within the class without being passed.

**Comment by Apogate** [comment]
Banned.php is intended to be a root level file, the host shouldn't have duplicates of it

**Comment by RePod** [comment]
> Only 209 lines in imgboard to go

**HUGE GAINS.** The Log class is longer, excluding Rebuild.

---

~~What actually uses $log? We could probably remove Log legacy commands (`updatelog()` and `log_cache()`) from the top-level (of _imgboard.php_) too.~~ 
~~Basically we could remove the legacy support if we switch everything over to the class calls.~~

~~For instance:~~
- ~~`log_cache()` to `$my_log->update_cache()`~~
- ~~`$log` to `$my_log->cache`~~
- ~~`updatelog()` to `$my_log->update()`~~

~~Currently `$my_log` is a top-level instance of the Log class would should stay where it is, but the legacy support should go (and possibly switch it to `$log`).~~

**DONE** a4f66cc22d32f9d8c2cc9f11dfc3a494e18b8e7d 02b12232de2243f4350db11ae7952ba9848be168

**Comment by Apogate** [comment]
Is this it? Can evil #64 finally be closed?

**Comment by RePod** [comment]
Nope, _imgboard.php_ is still >0 lines.

**Comment by Apogate** [comment]
![lol](http://www.gomotes.com/emoticon/skype/skypeflag-finland.png)We're finnish here![lol](http://www.gomotes.com/emoticon/skype/skypeflag-finland.png)

**Comment by RePod** [comment]
RIP the King.
