### ISSUE TITLE
Cached index.html and numeric pages changes for URL rewriting.

### ISSUE THREAD

**Issue by RePod** [spootTheLousy/saguaro#66]
Currently the file structure is like so:
- _index.html_ (page 1)
- _1.html_ (page 2)
- etc.

By adding the following, simple rewrite rule to _.htaccess_ we can further improve navigation:
`RewriteRule ^(\d+)/?$ $1.html`

In this instance, _http://site.com/board/1_ would refer to _1.html_.

You may have already noticed the problem: _1.html_ is page 2. While these can be handled on their own by specifying a rewrite rule for all of them, making the filenames logical would be better to conform to one rule.

_index.html_ could possibly be copied to/from 1.html.

**Comment by Apogate** [comment]
Fixed in ec7bd52602898bf75781402b51080dfabf1bd0e9

**Comment by RePod** [comment]
How so?

**Comment by Apogate** [comment]
I have made a grave mistake

**Comment by Apogate** [comment]
Finally put this one to rest
