### ISSUE TITLE
Server testing/install file.

### ISSUE THREAD

**Issue by RePod** [spootTheLousy/saguaro#68]
**Original message synopsis:**

A testing server did not have GD installed and it was not clear through using saguaro, a testing file is needed.

---

Current status of _test.php_: [First time run.](//i.imgur.com/p0OypWm.jpg) [Second time run.](//i.imgur.com/fPbE5uy.jpg)
Previous: [First time run.](//i.imgur.com/uPVqjCO.jpg) [Second time run.](//i.imgur.com/mjs2cmR.jpg)
Old: ~~[First time run.](//i.imgur.com/s8fgDRD.jpg)~~ ~~[Second time run.](//i.imgur.com/NuF02Z9.jpg)~~

---
- [x] Auto-lock out by requiring a deletion of file. (_.FILENAME_lockout_ by default)
  - Originally planned to chmod itself to `0000`, but that is too hands-on for casual users.
  - Eventually want to make this user-selectable: click button, redirect to page with GET var, lock.
- [x] Tests the versions of PHP, GD, and MySQL.
- [x] Displays relevant PHP Core Directives. #92
- [x] If MySQL is good to go, creates: (does not use old `table_exist()`)
  - [x] The database. (with config name, users previously had to do this manually)
  - [x] The tables. (with config names)
  - `report`, `loginattempts` and `rebuildqueue` table names are hard-coded as they do not exist in the config.
- [x] Creates working directories ("res", "src",  "thumb", etc.) (with config names) and chmods them to 0777.
  - [ ] [Recursive?](//php.net/manual/en/function.chmod.php#87826)
- [x] Creates working files (boardlist, news, etc.)
- [ ] Make headless?
- [ ] Check/set permissions of current directory.
  - Might not have to if the user can already access _test.php_.
- [ ] Set permissions of non-temporary files/folders, like _core or plugins, to something a bit safer.
  - Prevents something from accidentally nuking them (except acts of God).

---

~~Any mismatched functionality (like `get_gd_ver()` in [_core/regist/thumb.php](//github.com/spootTheLousy/saguaro/blob/master/_core/regist/thumb.php)) should be removed.~~ **DONE**

@Apogate can handle cleaning up _imgboard.php_.

**Comment by Apogate** [comment]
Couldn't this be integrated into an install file? Might as well run the dependency checks while saguaro sets up SQL and directories

**Comment by RePod** [comment]
It could be part of an install process, yes.

Testing LAMPPIX ~~next~~ eventually.

**Comment by RePod** [comment]
*test.php* output currently looks like this: 

![](//i.imgur.com/XVPUBFf.png)

**Comment by RePod** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7897871/8766563/f64e37a0-2e0a-11e5-971e-4090d24798f0.png)

**Comment by RePod** [comment]
Initial message updated with status and to-do list.

**Comment by Apogate** [comment]
* [ ] Remove SQL table inserts from imgboard
* [ ] Set up check for .test_lockout existence , if not either:
     * [ ] Set up prompts to direct user to test.php, die imgboard

**Comment by RePod** [comment]
Can probably remove the _src/_ and _thumb/_ directories from the repository since this will create them. Also _res/_ was being created automatically so any concerns with it before are mitigated since they're all under one system.

RIP History.

**Comment by Apogate** [comment]
Would it be worth it to have test.php check if the config contains a 'CHANGEME' string and point it out to the user?

**Comment by RePod** [comment]
> Would it be worth it to have test.php check if the config contains a 'CHANGEME' string and point it out to the user?

Yes, but only when it has a few options needed to be changed to begin with. I'll post my ideas in #54.

**Comment by RePod** [comment]
Currently has an "uninstall mode" that drops the tables then the database, if the database is empty.

However, reports and loginattempts are hardcoded and intended to be shared across boards making this [hard to implement](//github.com/spootTheLousy/saguaro/issues/69#issuecomment-134388901).

**Comment by RePod** [comment]
Huge problem came up, and that is config's _MAX_KB_ does not mean anything. #92

Or to say, it does not mean anything if the PHP Core _upload_max_filesize_ option is less than it.
The test file has been updated to spit out that size and a few other important Core options.

**Comment by RePod** [comment]
_rebuildqueue_create_table()_ is only called by Rebuild functions to generate a SQL table, and only when it doesn't already exist resulting in a SQL query fail.

Could this be moved into _test.php_?

**Comment by Apogate** [comment]
@RePod Let me review the rebuild functions , but you can go ahead and move it on a branch for now

**Comment by RePod** [comment]
Rebuild is kill: b92760e5094926a3381c973034e3bf9f2cebadbd and bb827050189ac47b88ef256304859ca4d2019f25

**Comment by Apogate** [comment]
no

**Comment by Yushe** [comment]
test.php should encrypt passwords on the sql database.

**Comment by RePod** [comment]
Seems arbitrary as it'd have to be implemented at both ends (insert it and then verifying it logging in) and some users may not be satisfied with whatever the default encryption would be.

It's simpler to just hash/encrypt it themselves and use _test.php_ to insert it.

**Comment by Apogate** [comment]
Shouldn't we rename test.php install.php anyway? It's out of testing stage and would be less confusing to some people.

**Comment by RePod** [comment]
The name doesn't really matter.

It was originally intended just to ensure the environment could support Saguaro. But then I decided to consolidate a lot of the particular steps to the old "setup" process (such as database/table generation) to make it really casual.

So it both tests and installs.

**Comment by Apogate** [comment]
Its not a huge deal anyway. I thought naming it install would make the setup process a tiny bit more intuitive.

**Comment by RePod** [comment]
PHP minimum version requirement should be bumped up to 5.0 as we transition from `mysql` to `mysqli` or newer (since `mysql` is removed in PHP 7).

**Comment by Yushe** [comment]
So saguaro won't work with mysql anymore?

**Comment by RePod** [comment]
> So saguaro won't work with mysql anymore?

I'm actually making an abstraction layer so we can use whatever we want at any time: [_core/mysql/mysql.php](https://github.com/spootTheLousy/saguaro/blob/master/_core/mysql/mysql.php)

This will allow us to switch between MySQL, MySQLi, PDO, Flatfile, etc. easier while making sure everything that uses it gets the expected results.

**Comment by RePod** [comment]
~~Note to eventually create the _BOARDLIST_.~~ 48fee8e43ac4c0e771cdac8d75a5bce70bc1e087

**Comment by Yushe** [comment]
I had a great idea, why not change the board ban tables to just one whole ban table. It would make it easier to globally ban users.

**Comment by Apogate** [comment]
> I had a great idea, why not change the board ban tables to just one whole ban table. It would make it easier to globally ban users.

If you change the `SQLBANLOG` in a board config to share a table, you can already do this

**Comment by Yushe** [comment]
Yeah but would it function properly.
inb4 you should change the code.

**Comment by Apogate** [comment]
Why would it not function properly? It was designed to allow for that exact usage if the owner wanted. `SQLBANLOG` stores a unique entry for every board a user is banned on, or stores one entry for a global ban. If you just referenced your single ban table in the board config, it can easily be shared across multiple boards.

**Comment by RePod** [comment]
> Yeah but would it function properly.

That's not for us to figure out, definitely worth a shot though.

You can share a lot more than the bans table though.
If you were so inclined you could share all the tables.
Easiest way to accomplish this would be sharing a prefix.

However, this does not mean we'll support it.

**Comment by Apogate** [comment]
I'd assume it's safe to close this. Test is perfect on the inside, where it counts
