### ISSUE TITLE
Deletion password needs fixing

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#75]
Currently, the script does not automatically generate, save or even use the deletion password for a user:

TO DO:
- [ ] Script checks if the user has a password cookie, if not, it generates the pw in the _Password_ form field
- [ ] Script sets this password as a cookie
- [ ] Script automatically fills this password in the footer _Delete_ textfield from the cookie
- [ ] Script automatically fills the SAME password in the _Password_ form field

**Comment by RePod** [comment]
Users can delete other users posts? Or is user deletion not working?

**Comment by Apogate** [comment]
Users can delete posts if it was made from the sam IP, which is how it's supposed to be.

Users cannot use a password to delete their own posts however.

**Comment by Apogate** [comment]
To be addressed in #99
