### ISSUE TITLE
Log Module

### ISSUE THREAD

**Issue by RePod** [spootTheLousy/saguaro#77]
**To use:**
`require_once("_core/log/log.php");` as early in _imgboard.php_ as possible

__core/log/log.php_ acts as a proxy, defining the functions which then `require` the desired files.

It's not a class yet, but it's the first step in doing so: removing it from imgboard.php.

Only the following were relocated, and can be removed from _imgboard.php_:
- `log_cache()`
- `updatelog()`

_imgboard.php_ has not been touched, yet (aside from testing locally).

---

Current problems:
- [x] Index page ~~does not update properly~~, despite the res page being created.
  - ~~Either I'm getting serious caching issues or somehow this was resolved.~~ Need to research more.
  - Accessing Catalog fixes. (requires `updatelog()` before running)
  - Accessing _imgboard.php_ directly (which calls `updatelog()`) fixes.
  - Manually rebuilding/all does not.
  - Something to do with `rebuild()` not being available? f20272096a35bc0abe9b37b172ba389316717951
  - Possibly the inverse, `updatelog()` and `log_cache()` not being available to _admin.php_.

Current non-problems:
- [x] Catalog works fine (even showing the OPs not shown on the index pages)
  - Catalog uses `updatelog()`
- [x] Otherwise integrates fine, simply remove the old functions then require __core/log/log.php_
- [x] Res pages generate properly

**Comment by Apogate** [comment]
Rebuild is getting moved back into its rightful home in **imgboard.php** and will become re-available

**Comment by RePod** [comment]
Moving it back is actually bad, see my proxying comment in #69.
