### ISSUE TITLE
Posting Error

### ISSUE THREAD

**Issue by Yushe** [spootTheLousy/saguaro#84]
I am running on the beta branch.

When I try to post on my site it makes the shows the error below.

It does create the post but it doesn't upload the image and it doesn't redirect when you post.

Please help!

<code>= 1 ) { $maxposts = LOG_MAX; $maxthreads = ( PAGE_MAX > 0 ) ? ( PAGE_MAX \* PAGE_DEF ) : 0; //number of pages x how many threads per page if ( $maxthreads ) { $exp_order = 'no'; if ( EXPIRE_NEGLECTED == 1 ) $exp_order = 'root'; $result = mysql_call( "SELECT no FROM " . SQLLOG . " WHERE sticky=0 AND resto=0 ORDER BY $exp_order ASC" ); $threadcount = mysql_num_rows( $result ); while ( $row = mysql_fetch_array( $result ) and $threadcount >= $maxthreads ) { delete_post( $row['no'], 'trim', 0, 1 ); // imgonly=0, automatic=1, children=1 $threadcount--; } mysql_free_result( $result ); // Original max-posts method (note: cleans orphaned posts later than parent posts) } else { // make list of stickies $stickies = array(); // keys are stickied thread numbers $result = mysql_call( "SELECT no from " . SQLLOG . " where sticky=1 and resto=0" ); while ( $row = mysql_fetch_array( $result ) ) { $stickies[$row['no']] = 1; } $result = mysql_call( "SELECT no,resto,sticky FROM " . SQLLOG . " ORDER BY no ASC" ); $postcount = mysql_num_rows( $result ); while ( $row = mysql_fetch_array( $result ) and $postcount >= $maxposts ) { // don't delete if this is a sticky thread if ( $row['sticky'] == 1 ) continue; // don't delete if this is a REPLY to a sticky if ( $row['resto'] != 0 && $stickies[$row['resto']] == 1 ) continue; delete_post( $row['no'], 'trim', 0, 1, 0 ); // imgonly=0, automatic=1, children=0 $postcount--; } mysql_free_result( $result ); } } } ?></code>

**Comment by Apogate** [comment]
Hi there, seems to be an issue with **/_core/regist/prune_old.php**

If you'll open that file in a text editor, replace the opening `<?` tag at the top with `<?php`.

Save it and let us know if that fixes it.
Alternately, you can google "Enable short tag php". 

I'll push a fix for this right now if you don't want to do it on your own.

**Comment by Apogate** [comment]
#85

**Comment by Yushe** [comment]
Thanks it works now. :)

**Comment by Apogate** [comment]
No problem. Let us know if you find anything else B^)

**Comment by Yushe** [comment]
Oh yeah when is there going to be a fix for stickys?

Keep in mine I use the old beta branch what was removed from here.

**Comment by Apogate** [comment]
Do you happen to know what version #?

**Comment by Yushe** [comment]
It says at the bottom of the page saguaro 0.98.3b4.

**Comment by Apogate** [comment]
The current build _should_ havea working admin panel and in turn, have stickies

**Comment by Yushe** [comment]
I think not having the php tag broke it, it works fine now.

Anyway I have two questions:
1. How do you create more admin/mod accounts?
2. How do you ban users.

**Comment by RePod** [comment]
> 1. How do you create more admin/mod accounts?

For now, manually edit [these lines in test.php](https://github.com/spootTheLousy/saguaro/blob/master/test.php#L20-L22) (on your server) then rerun _test.php_ (delete _.test_lockout_).

Ensure there is a comma between entries:

``` PHP
$defaults = [ //Default accounts.
    ['name' => 'admin', 'pass' => 'guest', 'priv' => 'janitor_board,moderator,admin,manager', 'deny' => 'none'],
    ['name' => 'subadmin', 'pass' => '1234', 'priv' => 'janitor_board,moderator,admin,manager', 'deny' => 'none']
];
```

Alternatively, access the proper table from your SQL server and insert them manually.

**Comment by Yushe** [comment]
And how do you ban people?
