### ISSUE TITLE
Rebuilding is broken

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#87]
yeah

**Comment by RePod** [comment]
Pretty vague, where is it breaking from? Stack trace?

Are the rebuild functions still in _imgboard.php_?
Are you doing this automatically or from the admin panel?

**Comment by Apogate** [comment]
This was more of a reminder for me to expand on later (which is now)

Manually rebuilding from the admin panel currently formats all the pages without head() being called in the process. This probably has everything to do with me ripping out rebuild() without the subordinate functions.
