### ISSUE TITLE
MAX_KB and PHP Core upload_max_filesize conflict.

### ISSUE THREAD

**Issue by RePod** [spootTheLousy/saguaro#92]
~~_MAX_KB_ is a saguaro config option, which by default is `5048` (probably a typo of `2048`).~~ **DONE**

However, _upload_max_filesize_ is a PHP Core setting which cannot be changed during execution (~~to the best of my knowledge~~ **see below**) and requires editing PHP's INIs directly.

If the user intended to allow larger files by increasing _MAX_KB_ it would fail due to _upload_max_filesize_.

Example:

```
if ($uploaded_file_size <= MAX_KB && $uploaded_file_size <= upload_max_filesize)
    success
if ($uploaded_file_size <= MAX_KB && $uploaded_file_size > upload_max_filesize)
    fail
```

~~The easiest fix would be to fix the typo of `5048` to at least put it in line with _upload_max_filesize_'s default 2MB.~~ **DONE**

Also, due to caching issues the _MAX_KB_ size is not correct (in the submitted form data) until the page is re-cached.
This could be fixed somewhere in Regist.

---

There is no need to assist users with problems like these as it is beyond our scope.
I might make a wiki page for this and other problems though.

---

_upload_max_filesize_ and _post_max_size_ are **PHP_INI_PERDIR** directives.
_post_max_size_ _should_ be larger than _upload_max_filesize_ as the uploaded file is sent as POST.

**.htaccess:** (per-dir, relative to executing script)

```
php_value post_max_size 8M
php_value upload_max_filesize 8M
```

No success using `ini_set('upload_max_filesize', '8M');`.

**Comment by Apogate** [comment]
What's the deal with this? Just a matter of moving it to the wiki page?

**Comment by RePod** [comment]
It's a potential edge case for when users complain about increasing MAX_KB and it "not working".

**Comment by Apogate** [comment]
Can I safely move this to the wiki?

**Comment by RePod** [comment]
[Boom.](https://github.com/spootTheLousy/saguaro/wiki/Common-Problems-and-Solutions)
