### ISSUE TITLE
Regist - File detection regression?

### ISSUE THREAD

**Issue by RePod** [spootTheLousy/saguaro#93]
@malamut2014 pointed this out from parley's outdated fork.
- [Before](https://github.com/spootTheLousy/saguaro/blob/f9e27ac4ff7583cdcbceafc944c7cf0273bf17d9/imgboard.php#L846-L848)
- [After](https://github.com/spootTheLousy/saguaro/blob/72c5b6ddfe20b4972472f7729b55ee0fc0b0ca57/imgboard.php#L1464-L1467)
- [Now](https://github.com/spootTheLousy/saguaro/blob/master/_core/regist/regist.php#L165-L168)

The error thrown was changed from _S_BADFILEISBAD_ to _S_UPFAIL_.

Is there a reason to revert to this?
Seems the change is better since they were (unsupported) upload fails.

**Comment by malamut2014** [comment]
The problem is that getImagesize() doesn't support webm format. And it returns `$ext=".xxx"`

**Comment by malamut2014** [comment]
I think the best way is to check the extension of uploading file, then use ffmpeg to get dimensions of it, and if the file is not webm, use getImagesize() way to get its dimensions.

**Comment by RePod** [comment]
Just going to close this in favor of #86.
