### ISSUE TITLE
Options in regist() unreferenced in config

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#95]
Some things that are never used or available to set in config, but exist in **regist()**
- [ ] ENABLE_PDF
- [x] GIF_ONLY
- [ ] OEKAKI_BOARD

Pieces of these options are missing in some cases, (PDF handling, Oekaki board features entirely) but could be useful in the future if we wanted to add those entirely.

**Comment by RePod** [comment]
Getting the board to a state in which integrating these features easily should be a higher priority.

Basically the entire user post handling system would need to be improved to effortlessly add new "templates" and maintain compatibility.

**Comment by RePod** [comment]
~~ENABLE_PDF seems kind of pointless.~~

~~It may have been more relevant back in 2004 but I can't see its use today that couldn't be accomplished with standard image formats.~~

To me. **#DeveloperBias**

**Comment by Apogate** [comment]
ENABLE_PDF serves as the bool to allow PDF upload for boards. It's useful for boards with academic or instructional purpose like 4chan's /diy/, /sci/, /po/, /o/ etc

It can come in handy, and if I remember correctly, it doesn't take up a ridiculous number of lines in regist/whatever class-hell you banished image processing to.

**Comment by RePod** [comment]
Looked at /po/, I guess it does have a use.

However, I've been meaning to bring up this for a while.

We should probably switch to Imagemagick from GD. Along with PDF support, SVG support (specifically thumbnailing them, which GD can't do) would be simple.

To the best of my knowledge only thumbnailing uses GD, so **_core/regist/thumb/image.php** would need to be revised.

However, it seems GD is more common on installations so it's a toss-up. I don't want to include dependencies (gif2png).

**Comment by Apogate** [comment]
PDF and Oekkaki are a long way off, probably around the same time we add some kind of filesharing board, akin to /f/.

Maybe board modes that generate pages in different formats, allowing for things like text only boards or again, filesharing boards.
